
# Full Stack Production Docker Compose for marvin App
# This includes frontend, backend, PostgreSQL, and Neo4j services
version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    container_name: marvin-frontend
    image: ${DOCKER_USERNAME}/marvin-frontend:latest
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

  # Backend - FastAPI Application
  backend:
    container_name: marvin-backend
    image: ${DOCKER_USERNAME}/marvin-backend:latest
    ports:
      - "5009:5009"
    environment:
      # AI/LLM Configuration (if applicable)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5009"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


networks:
  default:
    name: marvin-network
    driver: bridge
